shuttle-hq/shuttle-docs

examples/axum.mdx
examples/poem.mdx
examples/rocket.mdx
examples/salvo.mdx
examples/serenity.mdx
examples/thruster.mdx
examples/tide.mdx
examples/tower.mdx
examples/warp.mdx
introduction/quick-start.mdx
tutorials/url-shortener.mdx

Counterpart of https://github.com/shuttle-hq/shuttle/pull/498

feat: interactive project initialisation

---

introduction/what-is-shuttle.mdx

I have spotted a small grammatical error with an apostrophe in the header and a couple of non-capitalised errors where it should presumably be capitalised, as well as fixing a typo on line 39 where it should read "shared" instead of "sshared".
There seems to be a small amount of ambiguity re: whether or not shuttle should be capitalised or not due to it being capitalised in some places and not in others, so I've just capitalised it anyway but if this is wrong then feel free to omit it.

Fixing small grammatical mistakes

---

community/contribute.mdx

+ add documentation for setting up the development environment on Windows
In the interest of making sure all of the documentation is up to date, this change has been made to reflect [this PR](https://github.com/shuttle-hq/shuttle/pull/555/commits/451124f637e3a49d4d5ae5b95d07b64fc0f26e3b) which details setting up the git config to checkout files as LF rather than CRLF to be able to run the shell scripts required for setting up the dev environment through the project's Makefile.

docs: add Windows docs for setting up dev environment

---

tutorials/authentication.mdx

The tutorial for the Axum authentication post on the Shuttle docs page has a bit of a typo in the markdown, where the header for the Registering our database portion at line 212 includes parts of the next sentence.
I have split it where I presume that it should be split, which is at the "Before our app" block.

fix: small issue with header in markdown

---

.github/workflows/replicate.yml
community/contribute.mdx

This workflow will replicate `CONTRIBUTING.md` from the main repo every day at 15:35 UTC (odd times have lower load). It will use the title from `CONTRIBUTING.md` but convert it to a frontmatter title, and insert a description. If there are any changes between the main repo doc and the docs `community/contribute.md` doc, a PR will be created with the changes. If there are more changes before the PR is merged, they will be pushed to the same PR. 
Ideally we would implement a trigger in the main repo when there are changes to `CONTRIBUTING.md` so we get the PR immediately, but this is still a pretty big improvement in convenience. So I suggest we optimize it with that at a later date.
PS. I also left in the option of manually dispatching, should urgent changes be necessary. 
First PR for …

ci: implement workflow to automatically replicate CONTRIBUTING.md

---

resources/shuttle-static-folder.mdx

The link to the GitHub repo in the "static files" example incorrectly linked to the websockets example.  I corrected the link so that it goes to the static files example.

Fixed link to static files example on GitHub

---

introduction/shuttle-commands.mdx

Hello,
Have taken a crack at updating the section of the docs which describe the CLI.  I thought I'd get a pull requst in so you could see progress so far.
Thanks,
~Jeff Mitchell

First draft of update to CLI doc

---

introduction/installation.mdx
introduction/quick-start.mdx
mint.json
support/installing-protoc.mdx
support/troubleshooting.mdx

We can't link to an accordion in troubleshooting, so I made it a standalone page.

feat: add protoc installation instructions

---

fullstack/saas-template.mdx
mint.json

The document is not currently in the mint.json file therefore it never gets linked.

fix: mint.json

---

resources/shuttle-aws-rds.mdx

I wasn't entirely certain where I was meant to put the feature flag, and I usually end up having to look up the syntax anyway. Cargo is nice in that it will edit `Cargo.toml` for you, so this change gives the end user a copy-paste friendly `cargo` command that will install `shuttle-aws-rds` with the feature flag they want.

Clarify installation of AWS RDS engines

---

introduction/shuttle-commands.mdx

As mentioned in https://github.com/shuttle-hq/shuttle/pull/985, this PR adds a short list of commands to the CLI docs. The commands aren't comprehensive, but they are the ones I find myself using the most often and might be handy for newcomers who are getting used to the CLI.

Add cookbook to CLI docs

---

resources/shuttle-static-folder.mdx

Provides information about how to work with static folders that are included in a `.gitignore` file.
It also provides information about how to work with `Cargo Workspaces`.
**NOTE for reviewers**: I'm not a native speaker, so I would appreciate a revision of the text in case something can be expressed in a more 'idiomatic` way.

docs(static): provide solutions for some caveats

---

resources/shuttle-aws-rds.mdx

Another little (and optional) change. I wasn't too sure if shuttle would keep the data stored in a DB across deployments/restarts or if I would need to find something to keep the data permanently. I couldn't find anything that was super explicit about this, but 🌸Rain🌸 (rainofthestorm) on discord helped me out.
Very happy to not include this one-liner if it's mentioned elsewhere in the docs or if those in the know think it's a bit over the top.

Add RDS permanence clarification

---

tutorials/databases-with-rust.mdx

Fixes minor nitpick where it says MongoDB but should actually say `shuttle-persist`.

docs: Fix "Databases with Rust" page minor error

---

tutorials/rest-http-service-with-axum.mdx

Fixes a macro error (where there should be a hash there is none)

fix: Macro syntax error

---

resources/shuttle-turso.mdx

I worked with Shuttle Turso this afternoon, and found an issue involving conflicting versions of the libsql-client dependency. @jonaro00 noted that it's pinned within Shuttle Turso at v0.30.1.  I though that a note in the docs was warranted.
~Jeff

Add note about libsql-client pinned version

---

configuration/shuttle-service-name.mdx
examples/rocket.mdx
introduction/quick-start.mdx
resources/overview.mdx
tutorials/databases-with-rust.mdx
tutorials/rest-http-service-with-axum.mdx

I stumbled upon a couple of typos when reading through the docs the other day, so I scanned the repo and found a few more. Nothing groundbreaking here!

docs: Fix various minor typos

---

tutorials/serverless-calendar-app.mdx

Replaced incorrect .png URLs with .avif.
(To see the incorrect .png URLs, search for ".png" https://docs.shuttle.rs/tutorials/serverless-calendar-app, and compare to https://endler.dev/2022/zerocal.)
Thank you for shuttle.rs.

Fixed image URLs in tutorials/serverless-calendar-app

---

support/faq.mdx

This partially addresses https://github.com/shuttle-hq/shuttle/issues/1125
We will have to remember to upgrade this when we are upgrading our pinned rust version, I will add this to the release template.

docs: document pinned rust version

---

tutorials/rest-http-service-with-axum.mdx

Some `derive` invocations were missing the leading `#`. Additionally, some code blocks weren't formatted with rustfmt.

Fix missing number signs and formatting

---

support/faq.mdx

Redoing this PR because I accidentally deleted the first one I did.  Addresses open Issue #162.

docs: fix typo in eu-west region number

---

mint.json
resources/shuttle-metadata.mdx

I added a new section under resources to cover metadata.  As @oddgrd suggested, I borrowed a lot from the shuttle-metadata crate docs. Not sure if the spot I chose was the best (under Resources) but I though this was a start.
This PR is related to Issue #168.

improvement: add section discussing Metadata

---

resources/shuttle-turso.mdx

I've updated the shuttle-turso docs section to remove the note about needing to downgrade to version 0.30.1 after installing the libsql-client.

chore: update docs and remove libsql-client note

---

examples/rocket-jwt-authentication.mdx
examples/rocket-postgres.mdx
examples/rocket-static-files.mdx
examples/rocket.mdx

I've updated the Rocket related documentation to match up with the changes to shuttle-examples, to reflect resolution to the changes related to rocket 0.5.0-rc.4. I also took the opportunity to update the shuttle version in the examples, if I saw it was out of date.

improvement: update for rocket rc.4

---

tutorials/url-shortener.mdx

I've updated the url-shortener article in the "How-to" section to reflect the latest rc4 version of Rocket. Also took the liberty of updating the year to 2023...makes the article seem a little more fresh :)
I'll update the blog version this evening.
~Jeff

improvement: update url-shortener article

---

examples/axum-postgres.mdx

The endpoints are ```todos``` but the curl endpoints query ```/todo```

docs: Update Curl Requests

---

getting-started/shuttle-commands.mdx

The cargo-shuttle cli does not align with what the documentation says.  This fixes that.

Fixed shell completion documentation

---

introduction/how-shuttle-works.mdx

This PR improves the wording in the introduction documentation

doc: Remove reduntant "we" in the sentence

---

getting-started/installation.mdx

Updates https://docs.shuttle.rs/getting-started/installation to add Windows install script instructions.
Depends on shuttle-hq/shuttle#1503 and shuttle-hq/www#220

Add windows install script instructions

---

configuration/environment.mdx

Trying to deploy crate using Return Position Impl Trait In Trait, with rust-version set to 1.75, the deployer nicely prints that the currently active rustc version is 1.74.0. I noticed that was different than the documented behaviour. I have not checked that the environment variables are updated accordingly in the enviroment, but this commit assumes that.

Update documented rust version

---

_snippets/check-examples.mdx
_snippets/other-frameworks.mdx
examples/actix-cookie-authentication.mdx
examples/actix-postgres.mdx
examples/actix-static-files.mdx
examples/actix-websocket-actorless.mdx
examples/actix.mdx
examples/axum-jwt-authentication.mdx
examples/axum-postgres.mdx
examples/axum-static-files.mdx
examples/axum-websockets.mdx
examples/axum.mdx
examples/poise.mdx
examples/rocket-postgres.mdx
examples/rocket-static-files.mdx
examples/rocket.mdx
examples/serenity.mdx

and some snippets
merge after https://github.com/shuttle-hq/shuttle/pull/1507 is released

update examples to axum 0.7

---

examples/rocket-postgres.mdx

Instead of curl http://localhost:8000/todos/<id> it needs to be curl http://localhost:8000/todo/<id>.
The same change applies to the POST request.
I just tried the example and after applying this change, the example worked as described

change todos to todo in route name

---

resources/shuttle-turso.mdx

shuttle-hq/shuttle-docs#254 was merged too early, we need to wait for the release first

revert: #254 was merged too soon

---

getting-started/local-run.mdx

Ref Discord help thread: https://discord.com/channels/803236282088161321/1230716219712344085
Local run documentation does not appear to be synced up with `shared-db` documentation with regards to ensuring that Docker is running.

docs: add note about Docker "os error 2" issues

---

resources/shuttle-shared-db.mdx

Correct a typo error in the word annotation

docs: fix macro annotation typo

---

resources/shuttle-qdrant.mdx

Incorrect `local_addr` is replaced with the correct `local_url`.
See the [definition](https://github.com/shuttle-hq/shuttle/blob/05372f0965d02b3ef4d3718ffe1328c027a78b19/resources/qdrant/src/lib.rs#L12-L19) of `shuttle_qdrant::Qdrant`.
@joshua-mo-143

Correct parameter name.

---

docs/local-run.mdx

Local run docs still use `cargo watch -x 'shuttle run'`, which translates to `cargo shuttle run`; instead of using `cargo watch -s 'shuttle run'`, which translates to `shuttle run`.
This is just a quick fix to the docs.

docs: local-run.mdx still suggests running shuttle as cargo command instead of shell command

---

docs/local-run.mdx
examples/rocket-jwt-authentication.mdx
templates/fullstack/saas-template.mdx
templates/tutorials/authentication.mdx
templates/tutorials/send-your-logs-to-datadog.mdx
templates/tutorials/serverless-calendar-app.mdx
templates/tutorials/websocket-chat-app-js.mdx

Fixes all broken external links

fix: broken external links

---

migrations/frameworks/actix-web.mdx
migrations/frameworks/axum.mdx
migrations/frameworks/rocket.mdx

- Makes all of the dependencies generic (the latest version)
- Fixes a small typo issue

fix: migration typos

---

migrations/frameworks/custom-service.mdx
mint.json

Fixes the blog redirect link to not be a permanent SEO fix and an async-trait implementation on the Custom Service page.

fix: blog redirect link, async-trait

---

docs/telemetry/betterstack.mdx
docs/telemetry/getting-started.mdx

Updates documentation to clarify details about Betterstack telemetry integration.

Clarify Betterstack telemetry documentation

---

docs.json
docs/scaling.mdx
pricing/scaling.mdx

Adds an example how to change the instance size of your application.
Adds a page to the `./docs` subdirectory and links to that from the pricing scaling page.

docs: Add instance_size example

---

resources/shuttle-aws-rds.mdx
resources/shuttle-shared-db.mdx

feat: clarify shared pg limitations, rds pricing
