shuttle-hq/shuttle-docs

community/get-involved.mdx
introduction/welcome.mdx

We at Mintlify introduced an updated syntax for [adding icons](https://mintlify.com/docs/components/card). No changes are present on the docs.
Before
```jsx
<Card
icon={regular("name")}
/>
```
Now
```jsx
<Card
icon="name"
/>
```
An optional `iconType` can be specified to define the type of the icon

Update Icon Syntax

---

README.md
introduction/shuttle-commands.mdx
introduction/telemetry.mdx
mint.json

Add a section on how to use tracing/log with shuttle apps.
Closes #9

Feat: telemetry section

---

introduction/what-is-shuttle.mdx

Good evening,
Redoing the pull request from last night.  This time I think I got it right, no extra files because of differing Yarn versions.  I edited the "Infrastructure as Code" commentary on the "What is Shuttle?" page.
Thanks for your patience and tips so far. :)
Cheers,
~Jeff Mitchell

Edited "Infrastructure as Code" commentary

---

examples/custom-service.mdx

* Updates the custom service docs so that it now details how to create a custom service that will serve a Discord bot alongside a web server created using Axum.
Ref: Issue #12

docs: update custom service docs

---

introduction/idle-projects.mdx
introduction/installation.mdx
introduction/quick-start.mdx
introduction/shuttle-commands.mdx
introduction/what-is-shuttle.mdx
support/faq.mdx
support/installing-protoc.mdx
support/troubleshooting.mdx

General proofreading and fixes.
The most notable change is the installation of `protoc`. The variable shenanigans might be "too" fancy for a new user. Let me know if it should be simplified.

Clarify installation + docs fixes

---

configuration/shuttle-service-name.mdx
mint.json
support/faq.mdx

Good morning,
I added a new section to the docs called "Configuration" and within that a new article called "Shuttle Service Name".  This article covers the purpose of Shuttle.toml.  Please let me know what you think.  Will make any edits/changes if needed.
:)
Thanks,
~Jeff Mitchell

Chore: Add Shuttle.toml description

---

introduction/node-cli.mdx
introduction/what-is-shuttle.mdx
support/faq.mdx

The relevant change in the diff is in the FAQ.

feat: document compute resource caps

---

community/contribute.mdx
examples/poem.mdx
examples/rocket.mdx
examples/serenity.mdx
examples/shuttle-next.mdx
introduction/idle-projects.mdx
introduction/quick-start.mdx
introduction/shuttle-commands.mdx
support/faq.mdx
support/troubleshooting.mdx

Merge this when https://github.com/shuttle-hq/shuttle/pull/771 is released.

Update command descriptions and examples

---

introduction/quick-start.mdx

Add a note about https://github.com/shuttle-hq/shuttle/issues/821 to the quick-start docs.

docs: add note about init bug

---

resources/shuttle-static-folder.mdx

I've done some editing to the Shuttle Static Folder entry under the Resources section of the Shuttle docs page.
I added a few details to embellish the explanation and story for the feature.
~Jeff Mitchell

Edits to the Shuttle Static Folder discussion

---

resources/shuttle-static-folder.mdx

Hi everyone,
I took a further look at the edits to the Static Folder page under "Resources" and didn't like the way it flowed or read.  I did some editing just now to suggest some improvements.
I think it's easier to understand now.
~Jeff Mitchell

Edits to improve static folder page structure and readability

---

resources/shuttle-persist.mdx

Hello,
Decided to do a deep dive on the Shuttle Persist resource, in advance of me working the issue of adding .remove() and .list() methods. I noticed a couple of typos in the Shuttle Persist section of the docs, so I've fixed those and made some other embelishments.
~Jeff Mitchell

docs: Update shuttle-persist.mdx

---

examples/actix.mdx
examples/rocket.mdx
introduction/how-shuttle-works.mdx
introduction/idle-projects.mdx
introduction/telemetry.mdx
shuttle-next/overview.mdx
support/faq.mdx
support/troubleshooting.mdx
tutorials/authentication.mdx
tutorials/custom-service.mdx
tutorials/discord-weather-forecast.mdx
tutorials/url-shortener.mdx
tutorials/websocket-chat-app-js.mdx

- Capitalises Shuttle as required.
- Changes wording from alpha to beta where required.

docs: capitalise Shuttle; change 'alpha' to 'beta' where required

---

examples/actix.mdx
introduction/what-is-shuttle.mdx

Just fixes a nitpick of mine. Accompanies https://github.com/shuttle-hq/shuttle/pull/1093.

chore: fix Actix Web typos

---

examples/actix-postgres.mdx
examples/actix-websocket-actorless.mdx
examples/actix.mdx
examples/axum-static-files.mdx
examples/axum-websockets.mdx
examples/axum.mdx
examples/poise.mdx
examples/rocket.mdx
examples/serenity-todo.mdx
examples/serenity.mdx
examples/shuttle-next.mdx
shuttle-next/getting-started.mdx
tutorials/custom-service.mdx
tutorials/url-shortener.mdx
tutorials/websocket-chat-app-js.mdx

chore: v0.24.0 release

---

introduction/local-run.mdx
resources/shuttle-static-folder.mdx
tutorials/authentication.mdx
tutorials/discord-weather-forecast.mdx
tutorials/url-shortener.mdx

refactor: fix broken SEO links

---

tutorials/databases-with-rust.mdx

sqlx/offline feature has been removed.
(the change in line 200 was unintended)

remove sqlx/offline and some redundant features

---

mint.json
resources/shuttle-persist.mdx

This is a start to updating the docs with the new methods for Persist, to go along with issue #169. There is more to do, ideally I'd like to create an example or two. I thought it might be best to get this basic info up fairly quickly and then go from there.
Side note: I changed the sub-heading under resources from Databases to Data Persistence, I thought it was more descriptive.

improvement: update with new persist methods

---

resources/overview.mdx

I quickly took care of adding a short blurb about Turso to the Resources -> Overview page. Not a huge deal, but it just felt like it needed to be complete :)

improvement: add turso to resources overview

---

configuration/logs.mdx

TODO: update the link to the custom tracing example when it's merged.

feat(logging): update our logging docs to reflect logger changes

---

examples/actix-static-files.mdx
examples/axum-static-files.mdx
examples/rocket-static-files.mdx

Fixes the wording of some parts to make it much more concise.

fix: typos

---

_snippets/pro-feature.mdx
configuration/domain-names.mdx
getting-started/quick-start.mdx
getting-started/shuttle-commands.mdx
mint.json
resources/shuttle-aws-rds.mdx
resources/shuttle-shared-db.mdx

...and some more corrections and updates

feat: expand CLI docs, add domain name

---

examples/axum-jwt-authentication.mdx
examples/examples.mdx
examples/serenity-todo.mdx
getting-started/quick-start.mdx
tutorials/discord-weather-forecast.mdx
tutorials/send-your-logs-to-datadog.mdx

I noticed small typos in the documentation and I've created a pull request to fix it.
Kindly review and merge it if it looks good.

Typo Fix in Documentation

---

examples/rocket-jwt-authentication.mdx
examples/rocket-postgres.mdx
examples/rocket-static-files.mdx
examples/rocket.mdx
tutorials/url-shortener.mdx

I updated all the Rocket things in the docs to reflect version 0.5.0 stable.
~Jeff

improvement: update Rocket content for 0.5 stable

---

examples/actix-postgres.mdx
examples/axum-postgres.mdx
examples/rocket-postgres.mdx
examples/serenity-todo.mdx
resources/shuttle-aws-rds.mdx
resources/shuttle-persist.mdx
resources/shuttle-shared-db.mdx
tutorials/databases-with-rust.mdx

docs: shared db + aws rds feature flag rework

---

resources/shuttle-turso.mdx

Small doc updates to go with https://github.com/shuttle-hq/shuttle/pull/1531.

docs(shuttle-turso): update docs to be up to date with new libsql client

---

resources/shuttle-turso.mdx

#254 was merged too soon, so we had to revert it. This PR reverts the revert, restoring the changes. Don't merge this until after the turso changes have been released.

revert: restore #254 changes

---

resources/shuttle-aws-rds.mdx

Show how RDS instances can have a custom database name

feat: RDS database name option

---

mint.json

fix: add sidebar databases icon

---

resources/shuttle-shared-db.mdx

Adding the official notice that we are currently deprecating Mongo.

refactor: mongo deprecation notice

---

mint.json

Update sidebar structure for LLM resources & added OpenAI

---

support/troubleshooting.mdx

Adds some extra questions and answers to the troubleshooting section.

feat: add some q&a to troubleshooting

---

migration/migrating-to-shuttle.mdx

docs: fix typo

---

docs/deployment-environment.mdx

Part of [PLA-634](https://linear.app/shuttle/issue/PLA-634/shuttle-docs-for-docsshuttledev)

docs: Add community tier warning for spot interruptions

---

docs/domain-names.mdx

Clarify documentation on how to get public IPs for a Shuttle project, and remove the hardcoded IPs for the default load balancer.

feat: generalize custom domain A record docs
